#Requires -Version 7.0
<#
.SYNOPSIS
    Generates a folder of PowerShell test scripts for exercising
    Deploy-IntuneScripts.ps1 end to end against a real dev tenant.

.DESCRIPTION
    This does NOT talk to Graph and does NOT deploy anything. It only writes
    .ps1 files (plus a CHECKLIST.md) under -OutputPath. You then run the real
    Deploy-IntuneScripts.ps1 yourself against the generated folders, against a
    dev tenant, and use the checklist to confirm each script landed in Intune
    the way its name and console output say it should.

    Three folders are generated, each a separate -Path root for
    Deploy-IntuneScripts.ps1:

      generated/main/            - run with no extra flags
      generated/allow-override/  - run with -AllowTypeOverride
      generated/expect-failure/  - run with -DryRun; the wizard should THROW
                                    before creating anything (duplicate name,
                                    unknown group, conflicting group refs).

    Every generated script's body just Write-Hosts what it's testing - when
    deployed and run on a device/user in Intune, that's what you'll see in the
    script's run output.

    Group-dependent tests (#group:/#excludegroup:) are only generated for the
    roles you've filled in in the metadata file; anything left blank is
    skipped and listed under "Skipped" in CHECKLIST.md.

.PARAMETER MetadataPath
    Path to the editable metadata JSON (group names/guids, run settings). If
    it doesn't exist yet, it's created from e2e-metadata.template.json and the
    script stops so you can fill it in.

.PARAMETER OutputPath
    Where to write the generated test folders. Wiped and rebuilt on every run
    (it's a build artifact, not source) unless -NoClean is passed.

.PARAMETER NoClean
    Don't delete an existing -OutputPath before generating; new files are
    added/overwritten in place instead.
#>
[CmdletBinding()]
param(
    [string]$MetadataPath = (Join-Path $PSScriptRoot 'e2e-metadata.json'),
    [string]$OutputPath = (Join-Path $PSScriptRoot 'generated'),
    [switch]$NoClean
)

$ErrorActionPreference = 'Stop'

# --------------------------------------------------------------------------
# Metadata: create from template on first run, otherwise load and gate on
# confirmDevTenant so nothing gets generated by accident.
# --------------------------------------------------------------------------
if (-not (Test-Path -LiteralPath $MetadataPath)) {
    $template = Join-Path $PSScriptRoot 'e2e-metadata.template.json'
    Copy-Item -LiteralPath $template -Destination $MetadataPath
    Write-Host "Created $MetadataPath from the template." -ForegroundColor Yellow
    Write-Host "Edit it (group names/guids, confirmDevTenant) then re-run this script." -ForegroundColor Yellow
    exit 0
}

$metadata = Get-Content -LiteralPath $MetadataPath -Raw | ConvertFrom-Json -AsHashtable

if (-not $metadata['answers']['confirmDevTenant']) {
    throw "'$MetadataPath': answers.confirmDevTenant is false. Set it to true in the metadata file " +
          "once you've confirmed the -Path you'll run Deploy-IntuneScripts.ps1 against points at a DEV tenant, then re-run this script."
}
$runPrefix = [string]$metadata['answers']['runPrefix']
if ([string]::IsNullOrWhiteSpace($runPrefix)) { $runPrefix = 'E2E' }

function Test-HasValue {
    param([string]$Value)
    return -not [string]::IsNullOrWhiteSpace($Value)
}

function Get-GroupField {
    param([string]$Role, [string]$Field)
    $g = $metadata['groups'][$Role]
    if (-not $g) { return '' }
    return [string]$g[$Field]
}

# --------------------------------------------------------------------------
# Output folder prep.
# --------------------------------------------------------------------------
if ((Test-Path -LiteralPath $OutputPath) -and -not $NoClean) {
    Write-Host "Clearing previous generated set at $OutputPath" -ForegroundColor DarkGray
    Remove-Item -LiteralPath $OutputPath -Recurse -Force
}
New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null

$checklist = [System.Collections.Generic.List[object]]::new()
$skipped   = [System.Collections.Generic.List[string]]::new()

function New-E2EScript {
    param(
        [Parameter(Mandatory)][string]$FullPath,
        [Parameter(Mandatory)][string]$DisplayName,
        [Parameter(Mandatory)][string]$Description,
        [string[]]$Directives = @(),
        [switch]$NoDisplayNameDirective
    )
    $dir = Split-Path -Parent $FullPath
    New-Item -ItemType Directory -Path $dir -Force | Out-Null

    $lines = [System.Collections.Generic.List[string]]::new()
    if (-not $NoDisplayNameDirective) {
        $lines.Add("#scriptname:`"$DisplayName`"")
    }
    foreach ($d in $Directives) { $lines.Add($d) }
    $lines.Add('#startdesc')
    $lines.Add($Description)
    $lines.Add('#enddesc')
    $lines.Add('')
    # Single-quoted and escaped rather than interpolated: descriptions are
    # free text and must not be able to break out of the Write-Host literal.
    $escapedName = $DisplayName -replace "'", "''"
    $escapedDesc = $Description -replace "'", "''"
    $lines.Add("Write-Host 'E2E TEST: $escapedName'")
    $lines.Add("Write-Host '$escapedDesc'")

    Set-Content -LiteralPath $FullPath -Value ($lines -join "`n") -NoNewline
}

function Add-E2ETest {
    param(
        [Parameter(Mandatory)][string]$Root,
        [Parameter(Mandatory)][string]$RelPath,
        [Parameter(Mandatory)][string]$Title,
        [Parameter(Mandatory)][string]$Description,
        [Parameter(Mandatory)][string]$Expect,
        [string[]]$Directives = @(),
        [switch]$NoDisplayNameDirective
    )
    $displayName = "$runPrefix`: $Title"
    $fullPath = Join-Path (Join-Path $OutputPath $Root) $RelPath
    New-E2EScript -FullPath $fullPath -DisplayName $displayName -Description $Description `
        -Directives $Directives -NoDisplayNameDirective:$NoDisplayNameDirective

    $expectedName = if ($NoDisplayNameDirective) { [System.IO.Path]::GetFileNameWithoutExtension($RelPath) } else { $displayName }
    $checklist.Add([pscustomobject]@{
        Root        = $Root
        RelPath     = $RelPath
        DisplayName = $expectedName
        Expect      = $Expect
    })
}

# ==========================================================================
# main/  - run with: Deploy-IntuneScripts.ps1 -Path <main>
# ==========================================================================

# --- Folder-vs-#type resolution matrix, device/ and user/ -----------------
foreach ($folder in @('device', 'user')) {
    $other = if ($folder -eq 'device') { 'user' } else { 'device' }
    $runAs = if ($folder -eq 'device') { 'system' } else { 'user' }
    $otherRunAs = if ($other -eq 'device') { 'system' } else { 'user' }

    Add-E2ETest -Root 'main' -RelPath "$folder/01-baseline-no-type-comment.ps1" `
        -Title "$folder folder, no #type comment (baseline)" `
        -Description "Placed under $folder/ with no #type: comment at all." `
        -Expect "Type=$folder, RunAsAccount=$runAs, no warnings in console output."

    Add-E2ETest -Root 'main' -RelPath "$folder/02-type-matches-folder.ps1" `
        -Title "$folder folder, #type:$folder matches" `
        -Description "Placed under $folder/ with a #type:$folder comment that agrees with the folder." `
        -Expect "Type=$folder, RunAsAccount=$runAs, no warnings." `
        -Directives @("#type:$folder")

    Add-E2ETest -Root 'main' -RelPath "$folder/03-type-conflict-no-override.ps1" `
        -Title "$folder folder, #type:$other conflicts, no override" `
        -Description "Placed under $folder/ but the #type: comment says $other, and there is no #typeoverride:yes." `
        -Expect "Type=$folder (folder wins), RunAsAccount=$runAs. Deploy-IntuneScripts.ps1's own console output must show a 'conflicts with its' warning for this file." `
        -Directives @("#type:$other")

    Add-E2ETest -Root 'main' -RelPath "$folder/04-type-conflict-script-override.ps1" `
        -Title "$folder folder, #type:$other + #typeoverride:yes" `
        -Description "Placed under $folder/ with #type:$other AND #typeoverride:yes: the comment should win over the folder this time." `
        -Expect "Type=$other (comment wins, opposite of its own folder!), RunAsAccount=$otherRunAs, no warning." `
        -Directives @("#type:$other", '#typeoverride:yes')
}

# --- Loose (unsorted) scripts, alongside the folder-sorted ones above -----
Add-E2ETest -Root 'main' -RelPath '05-loose-type-user.ps1' `
    -Title 'Loose script (no folder), #type:user' `
    -Description 'Sits directly under the scan root, not in user/ or device/, with #type:user.' `
    -Expect 'Type=user, RunAsAccount=user, deployed alongside the folder-sorted scripts in the same run.' `
    -Directives @('#type:user')

Add-E2ETest -Root 'main' -RelPath '05-loose-type-device.ps1' `
    -Title 'Loose script (no folder), #type:device' `
    -Description 'Sits directly under the scan root, not in user/ or device/, with #type:device.' `
    -Expect 'Type=device, RunAsAccount=system, deployed alongside the folder-sorted scripts in the same run.' `
    -Directives @('#type:device')

Add-E2ETest -Root 'main' -RelPath '05-loose-no-type.ps1' `
    -Title 'Loose script (no folder), no #type comment' `
    -Description 'Sits directly under the scan root with no folder and no #type: comment - not deployable.' `
    -Expect "NOT deployed. Deploy-IntuneScripts.ps1's console output must show a 'Skipping ... no user/device folder and no #type' warning, and no matching object should appear in Intune."

# --- Optional fields, isolated one at a time -------------------------------
Add-E2ETest -Root 'main' -RelPath 'device/10-scriptname-falls-back-to-filename.ps1' `
    -Title 'scriptname falls back to filename' `
    -Description 'No #scriptname: comment. The Intune display name should come from the filename instead.' `
    -Expect "Intune display name is exactly the filename minus '.ps1': '10-scriptname-falls-back-to-filename'." `
    -NoDisplayNameDirective

Add-E2ETest -Root 'main' -RelPath 'device/11-noassignments.ps1' `
    -Title '#noassignments' `
    -Description 'Carries #noassignments - should be created with no assignment at all, not even the all-devices default.' `
    -Expect 'Script exists in Intune with zero assignments.' `
    -Directives @('#noassignments')

Add-E2ETest -Root 'main' -RelPath 'device/12-scriptcheck-yes.ps1' `
    -Title '#scriptcheck:yes' `
    -Description 'Carries #scriptcheck:yes. Compare against the baseline test (01), which leaves signature checking off.' `
    -Expect 'enforceSignatureCheck=true in Intune, versus false on the baseline script.' `
    -Directives @('#scriptcheck:yes')

Add-E2ETest -Root 'main' -RelPath 'device/13-host-64.ps1' `
    -Title '#host:64' `
    -Description 'Carries #host:64. Compare against the baseline test (01), which runs 32-bit by default.' `
    -Expect 'runAs32Bit=false in Intune, versus true on the baseline script.' `
    -Directives @('#host:64')

# --- Group-dependent tests: only generated for roles you filled in --------
$incName = Get-GroupField 'include' 'displayName'
$incGuid = Get-GroupField 'include' 'guid'
$incSecName = Get-GroupField 'includeSecondary' 'displayName'
$excName = Get-GroupField 'exclude' 'displayName'
$excGuid = Get-GroupField 'exclude' 'guid'

if (Test-HasValue $incName) {
    Add-E2ETest -Root 'main' -RelPath 'device/20-group-by-name.ps1' `
        -Title '#group: by display name' `
        -Description "Carries #group:`"$incName`". Should be assigned to that group only, not all devices." `
        -Expect "Assigned to group '$incName' only." `
        -Directives @("#group:`"$incName`"")
} else {
    $skipped.Add("device/20-group-by-name.ps1 - groups.include.displayName is blank in $MetadataPath")
}

if (Test-HasValue $incGuid) {
    Add-E2ETest -Root 'main' -RelPath 'device/21-group-by-guid.ps1' `
        -Title '#group: by guid' `
        -Description "Carries #group:$incGuid (bare guid, no name lookup needed)." `
        -Expect "Assigned to group guid $incGuid only." `
        -Directives @("#group:$incGuid")
} else {
    $skipped.Add("device/21-group-by-guid.ps1 - groups.include.guid is blank in $MetadataPath")
}

if ((Test-HasValue $incName) -and (Test-HasValue $incSecName)) {
    Add-E2ETest -Root 'main' -RelPath 'device/22-group-multiple.ps1' `
        -Title 'multiple #group: lines' `
        -Description "Carries two #group: lines: `"$incName`" and `"$incSecName`". Should be assigned to both." `
        -Expect "Assigned to both '$incName' and '$incSecName', nothing else." `
        -Directives @("#group:`"$incName`"", "#group:`"$incSecName`"")
} else {
    $skipped.Add("device/22-group-multiple.ps1 - needs both groups.include.displayName and groups.includeSecondary.displayName")
}

if ((Test-HasValue $excName) -or (Test-HasValue $excGuid)) {
    $excRef = if (Test-HasValue $excName) { "`"$excName`"" } else { $excGuid }
    $excLabel = if (Test-HasValue $excName) { $excName } else { $excGuid }
    Add-E2ETest -Root 'main' -RelPath 'device/23-excludegroup-only.ps1' `
        -Title '#excludegroup: alone (everyone except)' `
        -Description "Carries only #excludegroup:$excRef, no #group:. Should mean 'all devices except this group'." `
        -Expect "Assigned to all devices, with group '$excLabel' excluded." `
        -Directives @("#excludegroup:$excRef")
} else {
    $skipped.Add("device/23-excludegroup-only.ps1 - groups.exclude.displayName and groups.exclude.guid are both blank")
}

if ((Test-HasValue $incName) -and ((Test-HasValue $excName) -or (Test-HasValue $excGuid))) {
    $excRef = if (Test-HasValue $excName) { "`"$excName`"" } else { $excGuid }
    $excLabel = if (Test-HasValue $excName) { $excName } else { $excGuid }
    Add-E2ETest -Root 'main' -RelPath 'device/24-group-and-excludegroup.ps1' `
        -Title '#group: + #excludegroup: combined' `
        -Description "Carries #group:`"$incName`" and #excludegroup:$excRef." `
        -Expect "Assigned to group '$incName' with '$excLabel' excluded from it." `
        -Directives @("#group:`"$incName`"", "#excludegroup:$excRef")

    Add-E2ETest -Root 'main' -RelPath 'device/25-kitchen-sink.ps1' `
        -Title 'kitchen sink: description + group + excludegroup + scriptcheck + host64' `
        -Description "Combines a multi-line description, #group:`"$incName`", #excludegroup:$excRef, #scriptcheck:yes and #host:64 in one script." `
        -Expect "Assigned to '$incName' minus '$excLabel'; enforceSignatureCheck=true; runAs32Bit=false; description matches this text." `
        -Directives @("#group:`"$incName`"", "#excludegroup:$excRef", '#scriptcheck:yes', '#host:64')
} else {
    $skipped.Add("device/24-group-and-excludegroup.ps1 and device/25-kitchen-sink.ps1 - need groups.include and groups.exclude filled in")
}

# ==========================================================================
# allow-override/  - run with: Deploy-IntuneScripts.ps1 -Path <allow-override> -AllowTypeOverride
# Mirrors the 'conflict, no per-script override' case from main/, but here
# the CLI flag - not a script comment - is what's expected to flip the type.
# ==========================================================================
foreach ($folder in @('device', 'user')) {
    $other = if ($folder -eq 'device') { 'user' } else { 'device' }
    $otherRunAs = if ($other -eq 'device') { 'system' } else { 'user' }

    Add-E2ETest -Root 'allow-override' -RelPath "$folder/30-cli-override.ps1" `
        -Title "$folder folder, #type:$other conflicts, -AllowTypeOverride on the CLI" `
        -Description "Placed under $folder/ with #type:$other and NO #typeoverride:yes comment. This folder is meant to be run with -AllowTypeOverride." `
        -Expect "Type=$other (CLI flag wins, no per-script directive needed), RunAsAccount=$otherRunAs, no warning." `
        -Directives @("#type:$other")
}

# ==========================================================================
# expect-failure/  - run with: Deploy-IntuneScripts.ps1 -Path <expect-failure> -DryRun
# Every case here should make the wizard THROW during its pre-flight scan,
# before any script is created or updated. Self-contained, no metadata needed.
# ==========================================================================
# Add-E2ETest stamps the title into a unique-per-test name, so these two
# deliberately-colliding files are built by hand with New-E2EScript instead.
$dupPathA = Join-Path (Join-Path $OutputPath 'expect-failure') 'device/duplicate-name-a.ps1'
$dupPathB = Join-Path (Join-Path $OutputPath 'expect-failure') 'device/duplicate-name-b.ps1'
$dupName = "$runPrefix`: duplicate display name on purpose"
New-E2EScript -FullPath $dupPathA -DisplayName $dupName -Description 'Deliberately shares its display name with duplicate-name-b.ps1.'
New-E2EScript -FullPath $dupPathB -DisplayName $dupName -Description 'Deliberately shares its display name with duplicate-name-a.ps1.'
$checklist.Add([pscustomobject]@{ Root = 'expect-failure'; RelPath = 'device/duplicate-name-a.ps1'; DisplayName = $dupName; Expect = "Together with duplicate-name-b.ps1: run throws 'Duplicate display names ...' before creating anything." })
$checklist.Add([pscustomobject]@{ Root = 'expect-failure'; RelPath = 'device/duplicate-name-b.ps1'; DisplayName = $dupName; Expect = '(see duplicate-name-a.ps1)' })

Add-E2ETest -Root 'expect-failure' -RelPath 'device/group-ref-overlap.ps1' `
    -Title 'same group in both #group: and #excludegroup:' `
    -Description "Lists the same group name in both a #group: and an #excludegroup: line, which is a contradiction." `
    -Expect "Run throws '... group(s) listed as both #group: and #excludegroup: ...' before creating anything." `
    -Directives @('#group:"E2E-Overlap-Test-Group"', '#excludegroup:"E2E-Overlap-Test-Group"')

Add-E2ETest -Root 'expect-failure' -RelPath 'device/noassignments-plus-group.ps1' `
    -Title '#noassignments combined with #group:' `
    -Description '#noassignments and #group: together are a contradiction - one says nobody, the other says someone specific.' `
    -Expect "Run throws '... #noassignments cannot be combined with #group: ...' before creating anything." `
    -Directives @('#noassignments', '#group:"E2E-Should-Not-Matter"')

Add-E2ETest -Root 'expect-failure' -RelPath 'device/unknown-group-name.ps1' `
    -Title 'unknown group display name' `
    -Description "References a group name that should not exist in any tenant: #group:`"E2E-Definitely-Does-Not-Exist-$([guid]::NewGuid().ToString('N').Substring(0,8))`"." `
    -Expect 'Run throws during group resolution (unknown/unresolvable group name) before creating anything.' `
    -Directives @("#group:`"E2E-Definitely-Does-Not-Exist-Group`"")

# ==========================================================================
# Checklist + summary.
# ==========================================================================
$checklistPath = Join-Path $OutputPath 'CHECKLIST.md'
$md = [System.Collections.Generic.List[string]]::new()
$md.Add('# E2E test checklist')
$md.Add('')
$md.Add("Generated with runPrefix '$runPrefix'. Run each root, then tick off its rows once you've confirmed the Expect column against Intune / the console output.")
$md.Add('')
foreach ($root in @('main', 'allow-override', 'expect-failure')) {
    $rows = $checklist | Where-Object { $_.Root -eq $root }
    if (-not $rows) { continue }
    $md.Add("## $root/")
    if ($root -eq 'main') { $md.Add('Run: `Deploy-IntuneScripts.ps1 -Path <path-to-main>`') }
    if ($root -eq 'allow-override') { $md.Add('Run: `Deploy-IntuneScripts.ps1 -Path <path-to-allow-override> -AllowTypeOverride`') }
    if ($root -eq 'expect-failure') { $md.Add('Run: `Deploy-IntuneScripts.ps1 -Path <path-to-expect-failure> -DryRun` (should throw, nothing created)') }
    $md.Add('')
    foreach ($row in $rows) {
        $md.Add("- [ ] **$($row.RelPath)** -> $($row.DisplayName)")
        $md.Add("      Expect: $($row.Expect)")
    }
    $md.Add('')
}
if ($skipped.Count -gt 0) {
    $md.Add('## Skipped (fill in the metadata file to include these)')
    foreach ($s in $skipped) { $md.Add("- $s") }
}
Set-Content -LiteralPath $checklistPath -Value ($md -join "`n")

Write-Host ""
Write-Host "Generated $($checklist.Count) test script(s) under $OutputPath" -ForegroundColor Green
if ($skipped.Count -gt 0) {
    Write-Host "$($skipped.Count) group-dependent test(s) skipped - see CHECKLIST.md, or fill in $MetadataPath and re-run." -ForegroundColor Yellow
}
Write-Host ""
Write-Host "Checklist: $checklistPath"
Write-Host ""
Write-Host "Next steps (against your DEV tenant):"
Write-Host "  1. pwsh Deploy-IntuneScripts.ps1 -Path `"$OutputPath/main`""
Write-Host "  2. pwsh Deploy-IntuneScripts.ps1 -Path `"$OutputPath/allow-override`" -AllowTypeOverride"
Write-Host "  3. pwsh Deploy-IntuneScripts.ps1 -Path `"$OutputPath/expect-failure`" -DryRun   (expect it to throw)"
